author: andreadelfante
author_url: https://twitter.com/a_delfante
github_url: https://github.com/andreadelfante/SwiftEssentialsKit
root_url: https://andreadelfante.github.io/SwiftEssentialsKit
module: SwiftEssentialsKit
output: docs
theme: fullwidth
clean: true

exclude:
  - "**/*.generated.swift"

xcodebuild_arguments:
  - "-workspace"
  - "Example/SwiftEssentialsKit.xcworkspace"
  - "-scheme"
  - "SwiftEssentialsKit-Example"
