disabled_rules:
  - operator_whitespace

included:
  - SwiftEssentialsKit

excluded:
  - Example/Pods
  - SwiftEssentialsKit/UI/Generated/R.generated.swift

line_length: 300

file_length:
  warning: 500
  error: 1200

identifier_name:
  min_length: 2
  allowed_symbols: ["_"]

reporter: "emoji"
