name: "SwiftEssentialsKit CI"
on: [push, pull_request]

jobs:
  lint_podspec:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CultureHQ/actions-bundler
      - name: Linting podspec
        run: bundle exec fastlane podspec_lint
  lint_code:
    runs-on: macos-latest
    steps:
        - uses: actions/checkout@v2
        - uses: CultureHQ/actions-bundler
        - name: Linting podspec
          run: bundle exec fastlane code_lint
    needs: [lint_podspec]

  test_debug:
    runs-on: macos-latest
    steps:
        - uses: actions/checkout@v2
        - uses: CultureHQ/actions-bundler
        - name: Linting podspec
          run: bundle exec fastlane test_debug
    needs: [lint_podspec]

#  test_release:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/actions/before_run
#      - name: Linting podspec
#        run: bundle exec fastlane test_release
#    needs: [lint_podspec]
